<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" ignored="0" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="17908" started-at="2018-04-29T04:25:11Z" finished-at="2018-04-29T04:25:29Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="17908" started-at="2018-04-29T04:25:11Z" finished-at="2018-04-29T04:25:29Z">
      <class name="testcases.LoginTestCase2">
        <test-method status="PASS" signature="setupTestSuite()[pri:0, instance:testcases.LoginTestCase2@6f7fd0e6]" name="setupTestSuite" is-config="true" duration-ms="365" started-at="2018-04-29T09:55:11Z" finished-at="2018-04-29T09:55:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupTestSuite -->
        <test-method status="PASS" signature="startTest()[pri:0, instance:testcases.LoginTestCase2@6f7fd0e6]" name="startTest" is-config="true" duration-ms="6149" started-at="2018-04-29T09:55:11Z" finished-at="2018-04-29T09:55:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method status="FAIL" signature="login()[pri:0, instance:testcases.LoginTestCase2@6f7fd0e6]" name="login" duration-ms="10392" started-at="2018-04-29T09:55:17Z" finished-at="2018-04-29T09:55:28Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at pages.LoginPage.verifyTitleAfterLogin(LoginPage.java:59)
	at testcases.LoginTestCase2.login(LoginTestCase2.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="PASS" signature="endLogger(org.testng.ITestResult)[pri:0, instance:testcases.LoginTestCase2@6f7fd0e6]" name="endLogger" is-config="true" duration-ms="457" started-at="2018-04-29T09:55:28Z" finished-at="2018-04-29T09:55:28Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=login status=FAILURE method=LoginTestCase2.login()[pri:0, instance:testcases.LoginTestCase2@6f7fd0e6] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endLogger -->
        <test-method status="SKIP" signature="logout()[pri:0, instance:testcases.LoginTestCase2@6f7fd0e6]" name="logout" duration-ms="0" started-at="2018-04-29T09:55:28Z" depends-on-methods="testcases.LoginTestCase2.login" finished-at="2018-04-29T09:55:28Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method LoginTestCase2.logout()[pri:0, instance:testcases.LoginTestCase2@6f7fd0e6] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method LoginTestCase2.logout()[pri:0, instance:testcases.LoginTestCase2@6f7fd0e6] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logout -->
        <test-method status="PASS" signature="endTest()[pri:0, instance:testcases.LoginTestCase2@6f7fd0e6]" name="endTest" is-config="true" duration-ms="863" started-at="2018-04-29T09:55:28Z" finished-at="2018-04-29T09:55:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endTest -->
        <test-method status="PASS" signature="tearDownTestSuite()[pri:0, instance:testcases.LoginTestCase2@6f7fd0e6]" name="tearDownTestSuite" is-config="true" duration-ms="331" started-at="2018-04-29T09:55:29Z" finished-at="2018-04-29T09:55:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownTestSuite -->
      </class> <!-- testcases.LoginTestCase2 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
