<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" ignored="0" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="25967" started-at="2018-06-14T19:21:54Z" finished-at="2018-06-14T19:22:20Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="25967" started-at="2018-06-14T19:21:54Z" finished-at="2018-06-14T19:22:20Z">
      <class name="Testcases.LoginLogoutTC">
        <test-method status="PASS" signature="startTestSuite()[pri:0, instance:Testcases.LoginLogoutTC@42d80b78]" name="startTestSuite" is-config="true" duration-ms="1224" started-at="2018-06-14T15:21:52Z" finished-at="2018-06-14T15:21:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestSuite -->
        <test-method status="PASS" signature="startTest()[pri:0, instance:Testcases.LoginLogoutTC@42d80b78]" name="startTest" is-config="true" duration-ms="13728" started-at="2018-06-14T15:21:54Z" finished-at="2018-06-14T15:22:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method status="FAIL" signature="login()[pri:0, instance:Testcases.LoginLogoutTC@42d80b78]" name="login" duration-ms="8359" started-at="2018-06-14T15:22:07Z" finished-at="2018-06-14T15:22:16Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at pages.LoginPage.titleAfterLogin(LoginPage.java:55)
	at Testcases.LoginLogoutTC.login(LoginLogoutTC.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="PASS" signature="endLogger(org.testng.ITestResult)[pri:0, instance:Testcases.LoginLogoutTC@42d80b78]" name="endLogger" is-config="true" duration-ms="1225" started-at="2018-06-14T15:22:16Z" finished-at="2018-06-14T15:22:17Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=login status=FAILURE method=LoginLogoutTC.login()[pri:0, instance:Testcases.LoginLogoutTC@42d80b78] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endLogger -->
        <test-method status="SKIP" signature="logout()[pri:0, instance:Testcases.LoginLogoutTC@42d80b78]" name="logout" duration-ms="0" started-at="2018-06-14T15:22:17Z" depends-on-methods="Testcases.LoginLogoutTC.login" finished-at="2018-06-14T15:22:17Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method LoginLogoutTC.logout()[pri:0, instance:Testcases.LoginLogoutTC@42d80b78] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method LoginLogoutTC.logout()[pri:0, instance:Testcases.LoginLogoutTC@42d80b78] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logout -->
        <test-method status="PASS" signature="endTest()[pri:0, instance:Testcases.LoginLogoutTC@42d80b78]" name="endTest" is-config="true" duration-ms="2462" started-at="2018-06-14T15:22:17Z" finished-at="2018-06-14T15:22:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endTest -->
        <test-method status="PASS" signature="tearDownTestSuite()[pri:0, instance:Testcases.LoginLogoutTC@42d80b78]" name="tearDownTestSuite" is-config="true" duration-ms="1613" started-at="2018-06-14T15:22:20Z" finished-at="2018-06-14T15:22:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownTestSuite -->
      </class> <!-- Testcases.LoginLogoutTC -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
